---
swagger: "2.0"
info:
  description: "A RESTful API for the BiR WADe project"
  version: "0.5"
  title: "BiR Swagger"
  contact: "Andrei R. Palihovici"
    email: "andrei.r.palihovici@info.uaic.ro"
    url: "https://www.linkedin.com/in/andrei-palihovici/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: bir.swagger.io
basePath: /BiR/api/
tags:
- name: "GitHub link"
  description: "Link to the project repository hosted on GitHub"
  externalDocs:
      url: "https://github.com/ileanapopa11/BigDataRetriever"
      description: "This is where the un-deployed project is currently being hosted"
- name: "Project url"
  description: "Link to the project url (WIP)"
  externalDocs:
      url: 'https://bir.me'
      description: "This is where the project will be deployed"
schemes:
- "https"
paths:
    /source:
        GET:
            tags:
            - "source"
            description: "Returns information about all the available data sources (currently WikiData and DBPedia)"
            responses:
                200:
                    description: "Query-able knowledge bases"
                    schema:
                        type: array
                400:
                    description: ""
    /source/{sname}:
        POST:
            responses:
                405: "Invalid input. Maybe route does not support this?"
        GET:
            tags:
            - "source"
            description: "Returns information about a specific data source"
            parameters:
                - name: "sname"
                  in: "path"
                  description: "Name of the affiliated KB source"
                  required: true
                  type: "string"
                  format: str
            produces:
                - "{sname}.json"
                - "{sname}.xml"
           responses:
               200:
                   description: "Succesful operation"
               400:
                   description: "Invalid source"
               404:
                   description: "Source path not found!"
    /property:
        GET:
            tags:
            - "property"
            description: "Returns information about all the available properties currently usable in queries"
            responses:
                200:
                    description: "All the available properties"
                    schema:
                        type: array
                400:
                    description: ""
                404:
                    description: "Path not found!"
    /property/p{id}:
        POST:
            responses:
                405: "Invalid input. Maybe route does not support this?"
        GET:
            tags:
            - "property"
            description: "Returns information about a specific data property"
            parameters:
                - name: "pid"
                  in: "path"
                  description: "Name of the property"
                  required: true
                  type: "string"
                  format: str
            produces:
                - "{pid}.json"
                - "{pid}.xml"
           responses:
               200:
                   description: "Succesful operation"
               400:
                   description: "Invalid property"
               404:
                   description: "Property path not found!"
    /item:
        GET:
            tags:
            - "item"
            description: "Returns some information about all the available items currently returnable in queries"
            responses:
                200:
                    description: "Random 20 items"
                    schema:
                        type: array
                400:
                    description: ""
                404:
                    description: "Path not found!"
    /property/q{id}:
        POST:
            responses:
                405: "Invalid input. Maybe route does not support this?"
        GET:
            tags:
            - "item"
            description: "Returns information about a specific item. Defaults to wikidata"
            parameters:
                - name: "qid"
                  in: "path"
                  description: "Name of the item"
                  required: true
                  type: "string"
                  format: str
            produces:
                - "{qid}.json"
                - "{qid}.xml"
           responses:
               200:
                   description: "Succesful operation"
               400:
                   description: "Invalid item"
               404:
                   description: "Property path not found!"
